name: CLStuff
main: de.craftlancer.clstuff.CLStuff
version: ${project.version}
api-version: 1.14
depend: [CLCore, CLFeatures]
softdepend: [DiscordSRV, CombatLogX, MythicMobs]
loadbefore: [WorldGuard]
commands:
  tablist:
    description: Commands for editing tablist
  itembuilder:
    description: Easy item editing in a command
  howtoplay:
    description: Gives you a how to play book.
  stats:
    description: Displays your total playtime.
  map:
    description: Displays the link to dynmap.
    aliases: livemap
  wiki:
    description: Displays the link to the wiki.
  ping:
    description: Displays a player's ping.
  nodropflag:
    description: Add | List | Remove items excluded in the nodropflag.
  cchelp:
    description: CraftCititzen help commands.
    aliases: chelp
  squest:
    description: Server quests
  time:
    description: Shows server time
  wild:
    description: Teleports to a random location
  countEntities:
    description: Debug command
  voteall:
    description: Opens all voting sites at once.
  rankings:
    description: Player rankings.
    aliases: ranking
  modeltoken:
    description: Model Tokens
  explonerf:
    description: Explosion based farms nerf
  recolor:
    description: Recolors blocks
  store:
    description: Link to the store
    aliases: buy
  craft:
    description: Opens a crafting table when you have one on your inventory.
    usage: §f[§4Craft§fCitizen]§e You need to have a Crafting Table in your inventory.
  dungeons:
    description: Gives you a dungeons tutorial book.
  arenagui:
    description: Create Arena GUIs
  giveclaimblocks:
    description: Sends claimblocks to another player.
    usage: /giveclaimblocks <target> <amount>
  centermap:
    description: Centers map
    usage: Run /centermap while holding a map, centers to where you stand
  heroes:
    description: Commands for heroes
  citizensets:
    description: Commands for citizensets
    aliases: csets
  emote:
    description: Commands for emotes
  adminshop:
    description: Adminshop commands
    usage: Run /adminshop [create|remove] and right click the block
  cmdupgrade:
    description: Reloads custom model data upgrade preventer config
  fixitems:
    description: Fixes your broken items
  connectionmessages:
    description: Command for login/logout messages
permissions:
  clstuff.centermap:
    default: false

  clstuff.craft:
    default: true

  clstuff.nodrop.admin:
    default: op

  clstuff.squest.admin:
    default: op
    children:
      clstuff.squest.create: true
      clstuff.squest.delete: true
      clstuff.squest.reward: true
      clstuff.squest.requirements: true
      clstuff.squest.description: true
      clstuff.squest.start: true
      clstuff.squest.exempt: true
  clstuff.squest.user:
    default: true
    children:
      clstuff.squest.list: true
      clstuff.squest.info: true
      clstuff.squest.progress: true
  clstuff.squest.create:
    default: false
  clstuff.squest.delete:
    default: false
  clstuff.squest.reward:
    default: false
  clstuff.squest.requirements:
    default: false
  clstuff.squest.description:
    default: false
  clstuff.squest.start:
    default: false
  clstuff.squest.list:
    default: false
  clstuff.squest.info:
    default: false
  clstuff.squest.progress:
    default: false
  clstuff.squest.exempt:
    default: false

  clstuff.modeltoken.admin:
    default: op
    children:
      clstuff.modeltoken.add: true
      clstuff.modeltoken.list: true
      clstuff.modeltoken.remove: true
      clstuff.modeltoken.getitem: true
      clstuff.modeltoken.gettoken: true
      clstuff.modeltoken.blacklist: true
      clstuff.modeltoken.blacklist.add: true
      clstuff.modeltoken.blacklist.list: true
      clstuff.modeltoken.blacklist.remove: true
  clstuff.modeltoken.add:
    default: false
  clstuff.modeltoken.list:
    default: false
  clstuff.modeltoken.remove:
    default: false
  clstuff.modeltoken.getitem:
    default: false
  clstuff.modeltoken.gettoken:
    default: false
  clstuff.modeltoken.blacklist:
    default: false
  clstuff.modeltoken.blacklist.add:
    default: false
  clstuff.modeltoken.blacklist.list:
    default: false
  clstuff.modeltoken.blacklist.remove:
    default: false

  clstuff.explonerf.admin:
    default: op
    children:
      clstuff.explonerf.removemat: true
      clstuff.explonerf.addmat: true
      clstuff.explonerf.create: true
      clstuff.explonerf.setlimit: true
      clstuff.explonerf.threshold: true
      clstuff.explonerf.delete: true
      clstuff.explonerf.info: true
  clstuff.explonerf.removemat:
    default: false
  clstuff.explonerf.addmat:
    default: false
  clstuff.explonerf.create:
    default: false
  clstuff.explonerf.setlimit:
    default: false
  clstuff.explonerf.threshold:
    default: false
  clstuff.explonerf.delete:
    default: false
  clstuff.explonerf.info:
    default: false
  clstuff.heroes.admin:
    default: op
  clstuff.citizenset.admin:
    default: op
  clstuff.itembuilder:
    default: op
  clstuff.emote.admin:
    default: op
  clstuff.emote.target:
    default: op
  clstuff.emote.bypasscooldown:
    default: op
  clstuff.connectionmessage.admin:
    default: op